# -*- coding: utf-8 -*-
"""two_choice_graphing_+_choice_behavior_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Htfj1cB3lS96yBR6QjUIAfqbg1GzPX83
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import sem
from scipy.ndimage import gaussian_filter1d

#BOX 1
def process_metrics_data(root_folder, save_path, plot_binned=False, export_binned_csvs=True, quartile_basis="Rolling_Preference_A", transition_check_range=(0, 4050)):
    metrics = {
        "Speed": 13,
        "Border_Distance": 8,
        "Rolling_Preference_A": 31,
        "Rolling_Preference_B": 32,
        "Port_Distance_A": 35,
        "Port_Distance_B": 36,
        "Acceleration_P": 1,
        "Acceleration_W": 2,
        "Angular_Acceleration": 4,
        "Angular_Velocity": 5
    }

    region_column_index = 30
    skip_region_metrics = ["Rolling_Preference_A", "Rolling_Preference_B"]

    y_axis_limits = {
        "Speed": (None, None),
        "Border_Distance": (None, None),
        "Rolling_Preference_A": (None, None),
        "Rolling_Preference_B": (None, None),
        "Port_Distance_A": (None, None),
        "Port_Distance_B": (None, None),
        "Acceleration_P": (None, None),
        "Acceleration_W": (None, None),
        "Angular_Acceleration": (None, None),
        "Angular_Velocity": (None, None)
    }
    region_y_axis_limits = {
        "Speed": (None, None),
        "Border_Distance": (None, None),
        "Port_Distance_A": (None, None),
        "Port_Distance_B": (None, None),
        "Acceleration_P": (None, None),
        "Acceleration_W": (None, None),
        "Angular_Acceleration": (None, None),
        "Angular_Velocity": (None, None)
    }
    region_ab_plot_limits = {
        "Speed": (None, None),
        "Border_Distance": (None, None),
        "Port_Distance_A": (None, None),
        "Port_Distance_B": (None, None),
        "Port_Distance_Side_Matched": (None, None),
        "Acceleration_P": (None, None),
        "Acceleration_W": (None, None),
        "Angular_Acceleration": (None, None),
        "Angular_Velocity": (None, None)
    }

    line_colors = {"default": "black", "A": "blue", "B": "green", "matched": "purple"}
    sem_colors = {"default": "gray", "A": "blue", "B": "green", "matched": "purple"}

    num_frames = 4050
    frames = list(range(1, num_frames + 1))

    all_metric_data = {}
    all_region_a_data = {}
    all_region_b_data = {}

    for metric_name, column_index in metrics.items():
        subjects = []
        metric_data = []
        region_A_data = []
        region_B_data = []

        for timestamp_folder in os.listdir(root_folder):
            timestamp_path = os.path.join(root_folder, timestamp_folder)
            if not os.path.isdir(timestamp_path):
                continue

            for subfolder in ["Top", "Bottom"]:
                folder_path = os.path.join(timestamp_path, subfolder, "Individual CSVs")
                if not os.path.exists(folder_path):
                    continue

                for file in os.listdir(folder_path):
                    if file.endswith("Annotated.csv"):
                        file_path = os.path.join(folder_path, file)
                        subject_name = f"{timestamp_folder}_{subfolder}_{file.replace(' Annotated.csv', '')}"

                        try:
                            df = pd.read_csv(file_path)
                            if df.shape[1] <= max(column_index, region_column_index):
                                continue

                            metric_column = df.iloc[:num_frames, column_index].copy()
                            region_column = df.iloc[:num_frames, region_column_index].copy()

                            metric_column.replace([np.inf, -np.inf], np.nan, inplace=True)
                            metric_column.interpolate(inplace=True)
                            metric_column.fillna(method='bfill', inplace=True)
                            metric_column.fillna(method='ffill', inplace=True)

                            subjects.append(subject_name)
                            metric_data.append(metric_column.values)

                            if metric_name not in skip_region_metrics:
                                region_a = np.where(region_column == 'A', metric_column, np.nan)
                                region_b = np.where(region_column == 'B', metric_column, np.nan)
                                region_A_data.append(region_a)
                                region_B_data.append(region_b)

                        except Exception as e:
                            print(f"Error reading {file_path}: {e}")

        all_metric_data[metric_name] = metric_data
        if metric_name not in skip_region_metrics:
            all_region_a_data[metric_name] = region_A_data
            all_region_b_data[metric_name] = region_B_data

        def save_and_plot(data_matrix, suffix, y_limit_dict, custom_metric_name=None):
            df = pd.DataFrame({'Frame': frames})
            for subject, data in zip(subjects, data_matrix):
                data = data[:len(frames)]
                if len(data) < len(frames):
                    data = np.pad(data, (0, len(frames) - len(data)), 'constant', constant_values=np.nan)

                df[subject] = data

            metric_label = custom_metric_name if custom_metric_name else metric_name
            csv_path = os.path.join(save_path, f"{metric_label}{suffix}.csv")
            df.to_csv(csv_path, index=False)

            if len(subjects) > 0:
                plt.figure(figsize=(10, 6))
                avg = df.iloc[:, 1:].mean(axis=1, skipna=True)
                err = sem(df.iloc[:, 1:], axis=1, nan_policy='omit')
                smoothed_avg = gaussian_filter1d(avg, sigma=10)
                smoothed_err = gaussian_filter1d(err, sigma=10)
                color_key = "matched" if "matched" in suffix.lower() else "default"
                plt.plot(frames, smoothed_avg, color=line_colors[color_key], label=f'Average {metric_label}')
                plt.fill_between(frames, smoothed_avg - smoothed_err, smoothed_avg + smoothed_err, color=sem_colors[color_key], alpha=0.5)
                plt.xlabel("Frames")
                plt.ylabel(f"{metric_label} Value")
                plt.title(f"Smoothed Average {metric_label} Over Time{suffix.replace('_', ' ')}")
                if y_limit_dict.get(metric_label) != (None, None):
                    plt.ylim(y_limit_dict[metric_label])
                plt.legend()
                plt.savefig(os.path.join(save_path, f"{metric_label}{suffix}.pdf"))
                plt.close()

        def plot_ab_together(region_a_data, region_b_data, title_suffix="", custom_metric_name=None):
            metric_label = custom_metric_name if custom_metric_name else metric_name
            df_a = pd.DataFrame(region_a_data).T
            df_b = pd.DataFrame(region_b_data).T
            avg_a = df_a.mean(axis=1, skipna=True)
            avg_b = df_b.mean(axis=1, skipna=True)
            sem_a = sem(df_a, axis=1, nan_policy='omit')
            sem_b = sem(df_b, axis=1, nan_policy='omit')
            sa = gaussian_filter1d(avg_a, sigma=10)
            sb = gaussian_filter1d(avg_b, sigma=10)
            se_a = gaussian_filter1d(sem_a, sigma=10)
            se_b = gaussian_filter1d(sem_b, sigma=10)
            plt.figure(figsize=(10, 6))
            plt.plot(frames, sa, color=line_colors['A'], label=f'{metric_label} A')
            plt.plot(frames, sb, color=line_colors['B'], label=f'{metric_label} B')
            plt.fill_between(frames, sa - se_a, sa + se_a, color=sem_colors['A'], alpha=0.3)
            plt.fill_between(frames, sb - se_b, sb + se_b, color=sem_colors['B'], alpha=0.3)
            plt.title(f"{metric_label} A + B over time{title_suffix}")
            plt.xlabel("Frames")
            plt.ylabel(f"{metric_label} Value")
            if region_ab_plot_limits.get(metric_label) != (None, None):
                plt.ylim(region_ab_plot_limits[metric_label])
            plt.legend()
            suffix = title_suffix.replace(" ", "_") if title_suffix else ""
            plt.savefig(os.path.join(save_path, f"{metric_label}_RegionAB_Overlay{suffix}.pdf"))
            plt.close()

        save_and_plot(metric_data, "_Data", y_axis_limits)
        if metric_name not in skip_region_metrics:
            save_and_plot(region_A_data, "_RegionA", region_y_axis_limits)
            save_and_plot(region_B_data, "_RegionB", region_y_axis_limits)
            plot_ab_together(region_A_data, region_B_data)

    def plot_port_distance_matched_overlay():
        try:
            df_a = pd.read_csv(os.path.join(save_path, "Port_Distance_A_RegionA.csv"))
            df_b = pd.read_csv(os.path.join(save_path, "Port_Distance_B_RegionB.csv"))
            avg_a = df_a.iloc[:, 1:].mean(axis=1, skipna=True)
            avg_b = df_b.iloc[:, 1:].mean(axis=1, skipna=True)
            sem_a = sem(df_a.iloc[:, 1:], axis=1, nan_policy='omit')
            sem_b = sem(df_b.iloc[:, 1:], axis=1, nan_policy='omit')
            sa = gaussian_filter1d(avg_a, sigma=10)
            sb = gaussian_filter1d(avg_b, sigma=10)
            se_a = gaussian_filter1d(sem_a, sigma=10)
            se_b = gaussian_filter1d(sem_b, sigma=10)
            plt.figure(figsize=(10, 6))
            plt.plot(frames, sa, color=line_colors['A'], label='Port Distance A (Region A)')
            plt.plot(frames, sb, color=line_colors['B'], label='Port Distance B (Region B)')
            plt.fill_between(frames, sa - se_a, sa + se_a, color=sem_colors['A'], alpha=0.3)
            plt.fill_between(frames, sb - se_b, sb + se_b, color=sem_colors['B'], alpha=0.3)
            plt.title("Port Distance A on A and B on B Over Time")
            plt.xlabel("Frames")
            plt.ylabel("Port Distance")
            if region_ab_plot_limits.get("Port_Distance_Side_Matched") != (None, None):
                plt.ylim(region_ab_plot_limits["Port_Distance_Side_Matched"])
            plt.legend()
            plt.savefig(os.path.join(save_path, "Port_Distance_Side_Matched_Overlay.pdf"))
            plt.close()
        except Exception as e:
            print(f"Failed to plot matched port distances overlay: {e}")

    plot_port_distance_matched_overlay()

    if plot_binned or export_binned_csvs:
        def bin_data(data_matrix, bin_size, reduce='mean'):
            df = pd.DataFrame(data_matrix).T
            grouped = df.groupby(df.index // bin_size)
            binned = grouped.sum().T if reduce == 'sum' else grouped.mean().T
            return binned

        for bin_size, label in [(150, "5sec"), (300, "10sec"), (450, "15sec")]:
            binned_all = {}
            binned_a = {}
            binned_b = {}
            for metric in metrics:
                if metric in all_metric_data:
                    binned_df = bin_data(all_metric_data[metric], bin_size)
                    binned_all[metric] = binned_df.mean(axis=0)
                if metric in all_region_a_data:
                    binned_df_a = bin_data(all_region_a_data[metric], bin_size)
                    binned_a[metric] = binned_df_a.mean(axis=0)
                if metric in all_region_b_data:
                    binned_df_b = bin_data(all_region_b_data[metric], bin_size)
                    binned_b[metric] = binned_df_b.mean(axis=0)
            pd.DataFrame(binned_all).to_csv(os.path.join(save_path, f"{label} binned variables.csv"), index=False)
            pd.DataFrame(binned_a).to_csv(os.path.join(save_path, f"{label} binned RegionA variables.csv"), index=False)
            pd.DataFrame(binned_b).to_csv(os.path.join(save_path, f"{label} binned RegionB variables.csv"), index=False)

    if export_binned_csvs:
        try:
            pref_index = all_metric_data.get(quartile_basis)
            if pref_index:
                all_pref_means = [np.nanmean(x) for x in pref_index]
                qcut = pd.qcut(all_pref_means, 4, labels=["first quartile", "second quartile", "third quartile", "fourth quartile"])
                quartile_subjects = pd.DataFrame({"Subject": subjects, "Quartile": qcut})
                quartile_subjects.to_csv(os.path.join(save_path, f"{quartile_basis}_quartile_assignments.csv"), index=False)

                for metric in metrics:
                    if metric not in all_metric_data:
                        continue

                    for q_label in qcut.categories:
                        indices = [i for i, q in enumerate(qcut) if q == q_label]
                        raw_df = pd.DataFrame({'Frame': frames})
                        for idx in indices:
                            if idx < len(subjects):
                                subj = subjects[idx]
                                raw_df[subj] = all_metric_data[metric][idx]
                        raw_df.to_csv(os.path.join(save_path, f"{metric}_{q_label}_quartile_raw.csv"), index=False)

                        for bin_size, bin_label in [(150, "5sec"), (300, "10sec"), (450, "15sec")]:
                            binned = raw_df.drop(columns=['Frame']).T.groupby(lambda x: int(x) // bin_size, axis=1).mean().T
                            binned.to_csv(os.path.join(save_path, f"{metric}_{q_label}_quartile_binned_{bin_label}.csv"), index=False)

                    if metric in all_region_a_data:
                        for q_label in qcut.categories:
                            indices = [i for i, q in enumerate(qcut) if q == q_label]
                            raw_df = pd.DataFrame({'Frame': frames})
                            for idx in indices:
                                if idx < len(subjects):
                                    subj = subjects[idx]
                                    raw_df[subj] = all_region_a_data[metric][idx]
                            raw_df.to_csv(os.path.join(save_path, f"{metric}_{q_label}_RegionA_quartile_raw.csv"), index=False)

                    if metric in all_region_b_data:
                        for q_label in qcut.categories:
                            indices = [i for i, q in enumerate(qcut) if q == q_label]
                            raw_df = pd.DataFrame({'Frame': frames})
                            for idx in indices:
                                if idx < len(subjects):
                                    subj = subjects[idx]
                                    raw_df[subj] = all_region_b_data[metric][idx]
                            raw_df.to_csv(os.path.join(save_path, f"{metric}_{q_label}_RegionB_quartile_raw.csv"), index=False)

        except Exception as e:
            print(f"Failed exporting quartile CSVs: {e}")

        try:
            quartile_colors = {
                "first quartile": ("blue", "lightblue"),
                "second quartile": ("green", "lightgreen"),
                "third quartile": ("orange", "moccasin"),
                "fourth quartile": ("red", "lightcoral")
            }
            for metric in metrics:
                if metric not in all_metric_data:
                    continue

                plt.figure(figsize=(10, 6))
                for q_label in qcut.categories:
                    indices = [i for i, q in enumerate(qcut) if q == q_label]
                    raw_df = pd.DataFrame([all_metric_data[metric][i] for i in indices if i < len(all_metric_data[metric])]).T
                    avg = raw_df.mean(axis=1, skipna=True)
                    se = sem(raw_df, axis=1, nan_policy='omit')
                    smoothed_avg = gaussian_filter1d(avg, sigma=10)
                    smoothed_se = gaussian_filter1d(se, sigma=10)
                    line_color, sem_color = quartile_colors[q_label]
                    seconds = np.array(frames) / 30
                    plt.plot(seconds, smoothed_avg, label=q_label, color=line_color)
                    plt.fill_between(seconds, smoothed_avg - smoothed_se, smoothed_avg + smoothed_se,
                                     color=sem_color, alpha=0.3)
                plt.title(f"{metric} by Quartile")
                plt.xlabel("Time (s)")
                plt.ylabel(f"{metric} Value")
                if y_axis_limits.get(metric) != (None, None):
                    plt.ylim(y_axis_limits[metric])
                plt.legend()
                plt.savefig(os.path.join(save_path, f"{metric}_Quartile_Overlay.pdf"), dpi=300)
                plt.close()
        except Exception as e:
            print(f"Failed quartile plotting: {e}")
process_metrics_data("", "", export_binned_csvs=True, plot_binned=False, quartile_basis="Rolling_Preference_B", transition_check_range=(0, 4050))

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import sem
from scipy.ndimage import gaussian_filter1d
# BOX 2
# THIS BOX GETS THE PER-ODOR RAW CSVS AND GRAPHS
def process_metrics_data(
    root_folder, save_path, plot_binned=False, export_binned_csvs=True,
    quartile_basis="Rolling_Preference_A", transition_check_range=(0, 4050),
    bin_size=450, fig_size=(5, 5), pdf_dpi=300,
    label_choice="Choice", label_post="Post-Choice",
    line_choice=15, line_post=45,
    label_fontsize=8, label_rotation=90
):
    num_frames = 4050
    frames = list(range(1, num_frames + 1))

    ratio_A_subjects = {}
    ratio_B_subjects = {}

    for timestamp_folder in os.listdir(root_folder):
        for subfolder in ["Top", "Bottom"]:
            subfolder_path = os.path.join(root_folder, timestamp_folder, subfolder)
            if not os.path.isdir(subfolder_path):
                continue

            merged_path = None
            for file in os.listdir(subfolder_path):
                if "Merged_Region" in file:
                    merged_path = os.path.join(subfolder_path, file)
                    break

            if not merged_path or not os.path.exists(merged_path):
                print(f"[SKIP] Merged_Region file not found in: {subfolder_path}")
                continue

            try:
                df = pd.read_csv(merged_path)
                if df.shape[1] <= 1:
                    print(f"[SKIP] File too narrow: {merged_path} → shape={df.shape}")
                    continue

                df = df.iloc[:num_frames, 1:]
                if df.empty:
                    print(f"[SKIP] Empty data after trimming: {merged_path}")
                    continue

                for col in df.columns:
                    col_data = df[col]
                    counts_A = col_data.eq('A').astype(int)
                    counts_B = col_data.eq('B').astype(int)

                    with np.errstate(divide='ignore', invalid='ignore'):
                        ratio_A = (counts_A - counts_B) / (counts_A + counts_B)
                        dropped = ratio_A.isna().sum()
                        ratio_A = ratio_A.dropna()
                        ratio_B = -ratio_A

                    subject_label = f"{timestamp_folder}_{subfolder}_{col}"
                    ratio_A_subjects[subject_label] = ratio_A.values
                    ratio_B_subjects[subject_label] = ratio_B.values

                    print(f"[OK] Loaded {subject_label} → {len(ratio_A)} frames (Dropped {dropped} NaNs)")

            except Exception as e:
                print(f"[ERROR] {merged_path}: {e}")

    def plot_preference_index(subject_data, label):
        df = pd.DataFrame({'Frame': frames[:num_frames], 'Time_s': [f / 30 for f in frames[:num_frames]]})
        for subject, data in subject_data.items():
            if len(data) < num_frames:
                data = np.pad(data, (0, num_frames - len(data)), constant_values=np.nan)
            df[subject] = data

        save_df = df.drop(columns=['Time_s'])
        save_df.to_csv(os.path.join(save_path, f"Raw_Ratio_{label}_Preference_Index_Over_Time.csv"), index=False)

        plt.figure(figsize=fig_size)
        avg = df.iloc[:, 2:].mean(axis=1)
        err = sem(df.iloc[:, 2:], axis=1, nan_policy='omit')
        smoothed_avg = gaussian_filter1d(avg, sigma=10)
        smoothed_err = gaussian_filter1d(err, sigma=10)

        plt.plot(df['Time_s'], smoothed_avg, color='blue' if label == 'A' else 'red')
        plt.fill_between(df['Time_s'], smoothed_avg - smoothed_err, smoothed_avg + smoothed_err,
                         color='lightblue' if label == 'A' else 'lightcoral', alpha=0.5)
        plt.ylim(-1, 1)
        plt.xlabel("Time (s)")
        plt.ylabel("Preference Index")
        plt.title(f"Smoothed Ratio {label} Preference Index Over Time")
        plt.xlim(df['Time_s'].iloc[0], df['Time_s'].iloc[len(smoothed_avg) - 1])

        ax = plt.gca()
        ax.spines['top'].set_visible(False)
        ax.spines['bottom'].set_visible(False)

        max_time = df['Time_s'].iloc[-1]
        ax.set_xticks(np.arange(0, max_time + 1, 15))

        ax.axvline(x=line_choice, color='gray', linestyle='--', linewidth=1)
        ax.axvline(x=line_post, color='gray', linestyle='--', linewidth=1)

        ax.axvspan(line_choice, line_post, color='gray', alpha=0.1)
        ax.text(line_choice, 0.95, label_choice, ha='left', va='top',
                fontsize=label_fontsize, rotation=label_rotation)

        ax.axvspan(line_post, df['Time_s'].iloc[-1], color='gray', alpha=0.05)
        ax.text(line_post, 0.95, label_post, ha='left', va='top',
                fontsize=label_fontsize, rotation=label_rotation)

        ax.legend().remove()
        plt.savefig(os.path.join(save_path, f"Ratio_{label}_Preference_Index_Over_Time.pdf"),
                    transparent=True, dpi=pdf_dpi)
        plt.close()

    plot_preference_index(ratio_A_subjects, "A")
    plot_preference_index(ratio_B_subjects, "B")

    def save_binned_csv(subject_data, label, bin_size=450):
        binned_df = pd.DataFrame()

        for subject, data in subject_data.items():
            if len(data) < num_frames:
                data = np.pad(data, (0, num_frames - len(data)), constant_values=np.nan)
            bins = []
            for start in range(0, num_frames, bin_size):
                end = min(start + bin_size, num_frames)
                bin_mean = np.nanmean(data[start:end])
                bins.append(bin_mean)
            binned_df[subject] = bins

        binned_df.index.name = 'Bin'
        binned_df.to_csv(os.path.join(save_path, f"Binned_Raw_Ratio_{label}_Preference_Index_Over_Time.csv"))

    save_binned_csv(ratio_A_subjects, "A", bin_size=bin_size)
    save_binned_csv(ratio_B_subjects, "B", bin_size=bin_size)

process_metrics_data("", "",
                     export_binned_csvs=False, plot_binned=False, quartile_basis="Rolling_Preference_B", transition_check_range=(0, 4050), bin_size=450, fig_size=(9, 5), pdf_dpi=300, label_choice="Choosing",
                     label_post="Post-Choice", line_choice=15, line_post=45, label_fontsize=10, label_rotation=45)

#BOX 3
# preference index per-condition (across both odors) graphs
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import sem
from scipy.ndimage import gaussian_filter1d

def process_combined(csv_folder):
    combined_df = None
    subject_counter = 0

    for file in os.listdir(csv_folder):
        if "Raw" in file and "Preference_Index_Over_Time" in file and file.endswith(".csv"):
            file_path = os.path.join(csv_folder, file)
            df = pd.read_csv(file_path)
            df_filtered = df.iloc[0:4050, :]

            valid_columns = []
            for column in df_filtered.columns[1:]:
                values = df_filtered[column].values
                sign_changes = np.diff(np.sign(values))
                if np.any(sign_changes != 0):
                    valid_columns.append(column)
                else:
                    print(f"[EXCLUDE] Column {column} in {file} has no transitions.")

            if combined_df is None:
                combined_df = df[valid_columns]
            else:
                combined_df = pd.concat([combined_df, df[valid_columns]], axis=1)

            subject_counter += len(valid_columns)
            print(f"[OK] Loaded {file} with {len(valid_columns)} valid subjects")

    if combined_df is None or subject_counter == 0:
        print("ERROR: No data found in Raw CSVs.")
        return None, None, None

    frames = np.arange(len(combined_df))
    seconds = frames / 30.0
    avg = combined_df.mean(axis=1)
    err = sem(combined_df, axis=1, nan_policy='omit')
    smoothed_avg = gaussian_filter1d(avg, sigma=10)
    smoothed_err = gaussian_filter1d(err, sigma=10)

    return seconds, smoothed_avg, smoothed_err

def combine_preference_index(
    csv_folder,
    output_path,
    mid_region_color='white',
    post_region_color='white',
    region_opacity=0.2,
    line_labels=('Choosing', 'Post-Choice'),
    figure_size=(9, 5),
    dpi=300
):
    seconds, avg, err = process_combined(csv_folder)

    if avg is None:
        print("ERROR: no data.")
        return

    plt.figure(figsize=figure_size)
    plt.plot(seconds, avg, label='Combined EA Preference', color='blue')
    plt.fill_between(seconds, avg - err, avg + err, color='lightblue', alpha=0.5)

    plt.ylim(-1, 1)
    plt.xlabel("Time Bins (s)")
    plt.ylabel("Preference Index")
    plt.title("W1118 Preference for EA relative to IAAc")
    plt.legend()

    stim_start = 15
    stim_end = 45

    plt.axvline(stim_start, color='gray', linestyle='--', linewidth=1)
    plt.axvline(stim_end, color='gray', linestyle='--', linewidth=1)
    plt.axvspan(stim_start, stim_end, color=mid_region_color, alpha=region_opacity)
    plt.axvspan(stim_end, seconds[-1], color=post_region_color, alpha=region_opacity)

    y_text_pos = 0.95
    plt.text(stim_start + 0.5, y_text_pos, line_labels[0], rotation=90,
             verticalalignment='top', fontsize=9, color='gray', transform=plt.gca().get_xaxis_transform())
    plt.text(stim_end + 0.5, y_text_pos, line_labels[1], rotation=90,
             verticalalignment='top', fontsize=9, color='gray', transform=plt.gca().get_xaxis_transform())

    max_time = seconds[-1]
    tick_locs = np.arange(15, max_time + 1, 15)
    plt.xticks(tick_locs)
    plt.xlim(0, max_time)

    ax = plt.gca()
    ax.spines['top'].set_visible(False)
    ax.spines['bottom'].set_visible(False)

    plt.savefig(output_path, transparent=True, dpi=dpi)
    plt.close()
    print(f"Combined preference index plot saved to {output_path}")

combine_preference_index(
    csv_folder="",
    output_path="",
    mid_region_color='white',
    post_region_color='white',
    region_opacity=0.25,
    line_labels=('Exploration', 'Choice'),
    figure_size=(9, 5),
    dpi=300
)

# BOX 4
# bout summary 15 sec bin graphs
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Constants
FPS = 30
TIME_WINDOWS = {f'{i*15}-{(i+1)*15}s': (i*15, (i+1)*15) for i in range(9)}

aggregated_EA_A = {}
aggregated_EA_B = {}
aggregated_IAAc_A = {}
aggregated_IAAc_B = {}
excluded_animals = []


def process_file(file_path, folder_label):
    df = pd.read_csv(file_path)
    results = {}
    total_frames = df.shape[0]

    for animal in df.columns:
        series = df[animal].astype(str)
        total_time_A = (series.str.strip().str.upper() == 'A').sum() / FPS
        total_time_B = (series.str.strip().str.upper() == 'B').sum() / FPS

        if total_time_A >= (total_frames / FPS) - 0.5 or total_time_B >= (total_frames / FPS) - 0.5 or total_time_A < 0.5 or total_time_B < 0.5:
            excluded_animals.append(f"{animal}_{folder_label}_{os.path.basename(file_path).replace('.csv','')}")
            continue

        for window_name, (start_s, end_s) in TIME_WINDOWS.items():
            start_frame = start_s * FPS
            end_frame = end_s * FPS
            if end_frame > total_frames:
                end_frame = total_frames

            df_window = series.iloc[start_frame:end_frame]
            bouts = {'A': [], 'B': []}

            current_side = str(df_window.iloc[0]).strip()
            bout_length = 1

            for side in df_window.iloc[1:]:
                side = str(side).strip()
                if side == current_side:
                    bout_length += 1
                elif side in bouts:
                    bouts[current_side].append(bout_length / FPS)
                    current_side = side
                    bout_length = 1
                else:
                    current_side = side
                    bout_length = 1

            if current_side in bouts:
                bouts[current_side].append(bout_length / FPS)

            unique_animal_id = f"{animal}_{folder_label}_{os.path.basename(file_path).replace('.csv','')}"

            if unique_animal_id not in results:
                results[unique_animal_id] = {}

            for side_key in ['A', 'B']:
                mean_bout = sum(bouts[side_key]) / len(bouts[side_key]) if bouts[side_key] else 0
                results[unique_animal_id][f'{side_key}_{window_name}'] = mean_bout

                if 'EA' in file_path:
                    if side_key == 'A':
                        aggregated_EA_A.setdefault(window_name, {})[unique_animal_id] = mean_bout
                    if side_key == 'B':
                        aggregated_EA_B.setdefault(window_name, {})[unique_animal_id] = mean_bout
                if 'IAAc' in file_path:
                    if side_key == 'A':
                        aggregated_IAAc_A.setdefault(window_name, {})[unique_animal_id] = mean_bout
                    if side_key == 'B':
                        aggregated_IAAc_B.setdefault(window_name, {})[unique_animal_id] = mean_bout

    return pd.DataFrame.from_dict(results, orient='index')

# Function to iterate through timestamp folders and process files
def process_directory(root_dir, output_dir, label_keyword):
    all_results = {}
    found_any = False

    for timestamp_folder in os.listdir(root_dir):
        timestamp_path = os.path.join(root_dir, timestamp_folder)
        if not os.path.isdir(timestamp_path):
            continue

        print(f"Checking folder: {timestamp_path}")

        for tb_folder in ['Top', 'Bottom']:
            tb_path = os.path.join(timestamp_path, tb_folder)
            if not os.path.isdir(tb_path):
                print(f"Missing {tb_folder} in {timestamp_path}")
                continue

            for file in os.listdir(tb_path):
                if 'Merged_Region' in file and file.lower().endswith('.csv'):
                    found_any = True
                    file_path = os.path.join(tb_path, file)
                    print(f"Processing file: {file_path}")
                    summary_df = process_file(file_path, tb_folder)
                    all_results.update(summary_df.to_dict(orient='index'))

    if not found_any:
        print(f"No Merged_Region CSVs found in: {root_dir}")

    final_df = pd.DataFrame.from_dict(all_results, orient='index')
    final_df.index.name = 'AnimalID'
    output_file = os.path.join(output_dir, f'{label_keyword}_AllAnimals_MeanBoutLength.csv')
    final_df.to_csv(output_file)
    print(f"Saved: {output_file}")


def plot_and_save_aggregated(output_dir, y_max=None, odor_off_shift=0, choosing_shift=0, post_choice_shift=0):
    # current EA group = EA-A + IAAc-B
    ea_data = {}
    for window in TIME_WINDOWS:
        ea_data[window] = {**aggregated_EA_A.get(window, {}), **aggregated_IAAc_B.get(window, {})}
    ea_df = pd.DataFrame(ea_data).T
    ea_csv = os.path.join(output_dir, 'EA_bout_length_ovr_time.csv')
    ea_df.to_csv(ea_csv)

    # current IAAc group = EA-B + IAAc-A
    iaac_data = {}
    for window in TIME_WINDOWS:
        iaac_data[window] = {**aggregated_EA_B.get(window, {}), **aggregated_IAAc_A.get(window, {})}
    iaac_df = pd.DataFrame(iaac_data).T
    iaac_csv = os.path.join(output_dir, 'IAAc_bout_length_ovr_time.csv')
    iaac_df.to_csv(iaac_csv)

    excluded_file = os.path.join(output_dir, 'Excluded_Animals.csv')
    pd.DataFrame({'ExcludedAnimalID': excluded_animals}).to_csv(excluded_file, index=False)
    print(f"Excluded animals saved: {excluded_file}")

    plt.figure(figsize=(10, 6))
    colors = {'EA': 'steelblue', 'IAAc': 'darkblue'}

    for label, df in zip(['EA', 'IAAc'], [ea_df, iaac_df]):
        means = df.mean(axis=1)
        sems = df.sem(axis=1)
        bins = list(df.index)

        plt.plot(bins, means, label=label, color=colors[label], linewidth=2)
        plt.fill_between(bins, means - sems, means + sems, alpha=0.075, color=colors[label])

    plt.xlim(bins[0], bins[-1])
    if y_max is not None:
        plt.ylim(0, y_max)
    plt.ylabel('Mean Bout Length (s)', fontsize=14, fontweight='bold')
    plt.xlabel('Time Bins', fontsize=14, fontweight='bold')
    plt.title('Canton-S sucrose-trained average bout length per time bin', fontsize=16, fontweight='bold')
    plt.legend()
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.yticks(np.arange(0, y_max + 1, 5))

    plt.axvline('15-30s', color='lightgray', linestyle='--')
    plt.axvline('45-60s', color='lightgray', linestyle='--')

    plt.axvspan('0-15s', '15-30s', color='white', alpha=0.3)
    plt.axvspan('15-30s', '45-60s', color='white', alpha=0.3)
    plt.axvspan('45-60s', bins[-1], color='white', alpha=0.3)

    if odor_off_shift == 0:
        plt.text('0-15s', y_max * 0.95, 'Odor Off', fontsize=12, ha='left')
    else:
        idx = bins.index('0-15s')
        plt.text(idx + odor_off_shift, y_max * 0.95, 'Odor Off', fontsize=12, ha='left')
    if choosing_shift == 0:
        plt.text('15-30s', y_max * 0.95, 'Choice', fontsize=12, ha='left')
    else:
        idx = bins.index('15-30s')
        plt.text(idx + choosing_shift, y_max * 0.95, 'Choice', fontsize=12, ha='left')
    if post_choice_shift == 0:
        plt.text('45-60s', y_max * 0.95, 'Post-Choice', fontsize=12, ha='left')
    else:
        idx = bins.index('45-60s')
        plt.text(idx + post_choice_shift, y_max * 0.95, 'Post-Choice', fontsize=12, ha='left')

    plt.savefig(os.path.join(output_dir, 'cSSUCbout.pdf'))
    plt.show()


def do_it(ea_dir, iaac_dir, output_dir, y_max=None, odor_off_shift=0, choosing_shift=0, post_choice_shift=0):
    os.makedirs(output_dir, exist_ok=True)
    print(f"Scanning EA directory: {ea_dir}")
    process_directory(ea_dir, output_dir, 'EA')
    print(f"Scanning IAAc directory: {iaac_dir}")
    process_directory(iaac_dir, output_dir, 'IAAc')
    plot_and_save_aggregated(output_dir, y_max, odor_off_shift, choosing_shift, post_choice_shift)


do_it('',
      '',
      '',
      y_max=15, odor_off_shift=0.1, choosing_shift=0.1, post_choice_shift=0.1)  # Set y_max=None to auto-scale

# BOX 5
# counts of A to B and B to A transitions per animal
import os
import pandas as pd

def analyze_transitions(root_folder, save_path, region_column_index, num_frames):
    transition_types = {
        "A to B transitions": ("A", "B"),
        "B to A transitions": ("B", "A"),
        "total transitions": None
    }
    transition_bins = [(150, "5sec"), (300, "10sec"), (450, "15sec")]

    transitions_by_type = {k: {} for k in transition_types}
    lengths_by_subject = {}
    exclusions = []

    for timestamp_folder in os.listdir(root_folder):
        timestamp_path = os.path.join(root_folder, timestamp_folder)
        if not os.path.isdir(timestamp_path):
            continue

        for subfolder in ["Top", "Bottom"]:
            folder_path = os.path.join(timestamp_path, subfolder, "Individual CSVs")
            if not os.path.exists(folder_path):
                continue

            for file in os.listdir(folder_path):
                if file.endswith("Annotated.csv"):
                    file_path = os.path.join(folder_path, file)
                    subject_name = f"{timestamp_folder}_{subfolder}_{file.replace(' Annotated.csv', '')}"
                    try:
                        df = pd.read_csv(file_path)
                        if df.shape[1] <= region_column_index:
                            continue
                        region_series = df.iloc[:num_frames, region_column_index].astype(str)
                        actual_length = len(region_series)
                        if actual_length < 4050:
                            exclusions.append({"File": file_path, "Length": actual_length})
                            print(f"Excluded {file_path} due to insufficient length ({actual_length} frames).")
                            continue
                        transitions = region_series.shift(1) + ">" + region_series
                        a2b = transitions[transitions == "A>B"].index.tolist()
                        b2a = transitions[transitions == "B>A"].index.tolist()
                        any_switch = sorted(a2b + b2a)

                        transitions_by_type["A to B transitions"][subject_name] = a2b
                        transitions_by_type["B to A transitions"][subject_name] = b2a
                        transitions_by_type["total transitions"][subject_name] = any_switch
                        lengths_by_subject[subject_name] = actual_length

                    except Exception as e:
                        print(f"Transition error in {file_path}: {e}")

    for label, data in transitions_by_type.items():
        if label == "total transitions":
            continue

        for bin_size, bin_label in transition_bins:
            bin_results = {}
            max_bins = 0
            for subject, indices in data.items():
                actual_length = lengths_by_subject[subject]
                bins = [0] * (actual_length // bin_size + 1)
                for idx in indices:
                    bin_idx = idx // bin_size
                    bins[bin_idx] += 1
                bin_results[subject] = bins
                max_bins = max(max_bins, len(bins))

            for subject in bin_results:
                bins = bin_results[subject]
                if len(bins) < max_bins:
                    bins.extend([0] * (max_bins - len(bins)))
                bin_results[subject] = bins

            df_out = pd.DataFrame.from_dict(bin_results, orient='columns')
            df_out = df_out.fillna(0).astype(int)
            csv_filename = f"{label.replace(' ', '_')}_{bin_label}.csv"
            output_path = os.path.join(save_path, csv_filename)
            df_out.to_csv(output_path, index=False)
            print(f"Saved: {output_path}")

    # Save total transitions count CSV
    total_transitions_data = transitions_by_type["total transitions"]
    total_counts = {subject: len(indices) for subject, indices in total_transitions_data.items()}
    df_out = pd.DataFrame(list(total_counts.items()), columns=["Subject", "Total_Transitions"])
    output_path = os.path.join(save_path, "total_transitions_count.csv")
    df_out.to_csv(output_path, index=False)
    print(f"Saved: {output_path}")

    if exclusions:
        exclusions_df = pd.DataFrame(exclusions)
        exclusions_path = os.path.join(save_path, "exclusions_log.csv")
        exclusions_df.to_csv(exclusions_path, index=False)
        print(f"Saved exclusions log: {exclusions_path}")


if __name__ == '__main__':
    root_folder = r""
    save_path = r""
    region_column_index = 30
    num_frames = 4050

    analyze_transitions(root_folder, save_path, region_column_index, num_frames)

# BOX 6
#5 SEC BIN AVERAGE transitions over time graphs
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


def compute_mean_sem(df: pd.DataFrame, exclude_zeros: bool):
    if exclude_zeros:
        df = df.mask(df == 0, np.nan)
    mean_vals = df.mean(axis=1, skipna=True).values
    sem_vals = df.std(axis=1, skipna=True).values / np.sqrt(df.count(axis=1))
    return mean_vals, sem_vals


def add_shaded_region(ax, start_time, end_time, color, label):
    ymin, ymax = ax.get_ylim()
    ax.axvspan(start_time, end_time, color=color, alpha=0.3, zorder=0)
    x_label_pos = (start_time + 1)
    ax.text(x_label_pos, ymax * 0.95, label, rotation=0,
            verticalalignment='top', horizontalalignment='left',
            fontsize=14, color='black', zorder=3)


def clean_and_sum_csvs(filepaths):
    cleaned_dfs = []
    for path in filepaths:
        try:
            df_raw = pd.read_csv(path, header=None, dtype=str, encoding='utf-8-sig')
        except UnicodeDecodeError:
            df_raw = pd.read_csv(path, header=None, dtype=str, encoding='latin1')

        def clean_cell(x):
            x_stripped = str(x).strip()
            if '*' in x_stripped:
                return np.nan
            try:
                return float(x_stripped)
            except ValueError:
                return np.nan

        cleaned_df = df_raw.applymap(clean_cell)
        cleaned_dfs.append(cleaned_df)

    summed_df = sum(cleaned_dfs)
    summed_df = summed_df.dropna(how='all', axis=0).dropna(how='all', axis=1)
    return summed_df


def average_two_csvs(csv1: str, csv2: str, output_path: str):
    df1 = pd.read_csv(csv1)
    df2 = pd.read_csv(csv2)
    df_avg = pd.DataFrame()
    df_avg['Mean'] = (df1['Mean'] + df2['Mean']) / 2
    df_avg['SEM'] = (df1['SEM'] + df2['SEM']) / 2
    df_avg.to_csv(output_path, index=False)
    return df_avg


def plot_graph(csv_folder: str, output_folder: str, graph_title: str, y_max: float = None, y_min: float = None, exclude_zeros: bool = False, max_bins: int = None, show_legend: bool = True):
    files = os.listdir(csv_folder)

    categories = {
        'EA': [],
        'IAAc': []
    }
    for f in files:
        for key in categories:
            if key.lower() in f.lower() and f.endswith('.csv') and 'summed' not in f.lower():
                categories[key].append(os.path.join(csv_folder, f))

    summed_paths = []
    for key, paths in categories.items():
        if len(paths) == 2:
            summed_df = clean_and_sum_csvs(paths)
            means, sems = compute_mean_sem(summed_df, exclude_zeros)
            out_df = summed_df.copy()
            out_df['Mean'] = means
            out_df['SEM'] = sems
            out_path = os.path.join(output_folder, f'{key}_summed.csv')
            out_df.to_csv(out_path, index=False)
            print(f"Summed CSV saved to {out_path}")
            summed_paths.append(out_path)
        else:
            print(f"Skipping {key}: expected 2 files, found {len(paths)}")

    if len(summed_paths) != 2:
        print("Expected exactly two valid summed CSVs to average.")
        return

    avg_csv_path = os.path.join(output_folder, 'final_averaged.csv')
    df_avg = average_two_csvs(summed_paths[0], summed_paths[1], avg_csv_path)

    means = df_avg['Mean'].values
    sems = df_avg['SEM'].values

    if max_bins is not None:
        means = means[:max_bins]
        sems = sems[:max_bins]

    bin_count = len(means)
    time_bins = np.arange(0, bin_count * 5, 5)

    fig, ax = plt.subplots(figsize=(12, 8))
    plt.subplots_adjust(bottom=0.2)
    ax.plot(time_bins, means, label='Averaged', color='#2b2b2b', linewidth=3)
    ax.fill_between(time_bins,
                    means - (sems / 2),
                    means + (sems / 2),
                    color='#2b2b2b',
                    alpha=0.075)

    ax.set_xlim(left=time_bins[0], right=time_bins[-1])
    if y_max is not None or y_min is not None:
        current_ylim = ax.get_ylim()
        ax.set_ylim(
            bottom=y_min if y_min is not None else current_ylim[0],
            top=y_max if y_max is not None else current_ylim[1]
        )
        print(f"Y-axis maximum set to {y_max}")

    add_shaded_region(ax, 0, 15, 'white', 'Odor Off')
    add_shaded_region(ax, 15, 45, 'white', 'Exploration')
    add_shaded_region(ax, 45, time_bins[-1] + 5, 'white', 'Choice')

    ax.axvline(x=15, color='gray', linestyle='--', linewidth=1, zorder=0)
    ax.axvline(x=45, color='gray', linestyle='--', linewidth=1, zorder=0)

    ax.set_title(graph_title, fontsize=18, fontweight='bold')
    ax.set_xlabel("Time Bins (sec)", fontsize=16, fontweight='bold')
    ax.set_ylabel("Transitions", fontsize=16, fontweight='bold')
    if show_legend:
        ax.legend(loc='upper right')

    xticks = np.arange(0, bin_count * 5, 5)
    xtick_labels = [f"{x}-{x+5}" if i % 3 == 0 else "" for i, x in enumerate(xticks)]
    ax.set_xticks(xticks)
    ax.set_xticklabels(xtick_labels, rotation=45, fontsize=14)

    ax.tick_params(axis='x', which='minor', bottom=False)  # Disable minor ticks
    ax.tick_params(axis='x', which='major', length=7)
    ax.tick_params(axis='y', labelsize=14)

    suffix = '_nozeros' if exclude_zeros else ''
    if max_bins is not None:
        suffix += f'_max{max_bins}'

    output_path = os.path.join(output_folder, f'output_graph{suffix}.pdf')
    plt.savefig(output_path)
    plt.close()
    print(f"Graph saved to {output_path}")


if __name__ == '__main__':
    csv_folder = input("Paste Google Drive folder path for CSVs: ").strip()
    output_folder = input("Paste Google Drive output folder path: ").strip()
    graph_title = input("Enter graph title: ").strip()
    y_max_input = input("Enter maximum Y-axis value (or leave blank for auto): ").strip()
    y_min_input = input("Enter minimum Y-axis value (or leave blank for auto): ").strip()
    max_bins_input = input("Enter max number of bins to graph (or leave blank for all): ").strip()
    legend_toggle = input("Show legend? (y/n): ").strip().lower()

    y_max = float(y_max_input) if y_max_input else None
    max_bins = int(max_bins_input) if max_bins_input else None
    y_min = float(y_min_input) if y_min_input else None
    show_legend = legend_toggle != 'n'

    try:
        plot_graph(csv_folder, output_folder, graph_title, y_max=y_max, y_min=y_min, exclude_zeros=False, max_bins=max_bins, show_legend=show_legend)
    except Exception as e:
        print(f"Failed to create plot (include zeros): {e}")

    try:
        plot_graph(csv_folder, output_folder, graph_title + " (Excluding Zeros)", y_max=y_max, y_min=y_min, exclude_zeros=True, max_bins=max_bins, show_legend=show_legend)
    except Exception as e:
        print(f"Failed to create plot (excluding zeros): {e}")

# BOX 7
# ORIENTATION PER 15 SECOND BIN AFTER TURNS AND COUNTS OF U-TURNS
import os
import re
import pandas as pd
import numpy as np
from pathlib import Path


FPS = 30
FRAMES_PER_BIN = 15 * FPS  # 450 frames per 15-second bin
START_ROW = 2
END_ROW = 4052
MIN_SHARP_TURN_FRAMES = int(0.15 * FPS)  # 5 frames

ANGLE_MIN = 4.0  # deg/.05s
SPEED_MIN = 5.0  # mm/s


def sharpturns(root_dir: str, output_csv: str, orientation_csv_A: str, orientation_csv_B: str,
                         pre_orientation_csv_A: str, pre_orientation_csv_B: str,
                         away_csv_A: str, away_csv_B: str):
    result = {}
    orientation_result_A = {}
    orientation_result_B = {}
    pre_orientation_result_A = {}
    pre_orientation_result_B = {}
    away_counts_A = {}
    away_counts_B = {}

    for ts_folder in Path(root_dir).iterdir():
        if not re.match(r"\d+\.\d+\.\d+", ts_folder.name):
            continue

        for side in ["Top", "Bottom"]:
            side_path = ts_folder / side / "Individual CSVs"
            if not side_path.exists():
                continue

            for csv_file in side_path.glob("*Annotated.csv"):
                subject_id = csv_file.stem.replace("Annotated", "").strip(" _-")
                subject_key = f"{ts_folder.name}_{side}_{subject_id}"

                try:
                    df = pd.read_csv(csv_file, skiprows=START_ROW, nrows=END_ROW - START_ROW + 1)
                except Exception as e:
                    print(f"Failed reading {csv_file}: {e}")
                    continue

                try:
                    acc = pd.to_numeric(df.iloc[:, 2], errors='coerce') * 10
                    speed = pd.to_numeric(df.iloc[:, 13], errors='coerce') * 10
                    angle = pd.to_numeric(df.iloc[:, 5], errors='coerce')
                    side_info = df.iloc[:, 30].astype(str)
                    orientation = pd.to_numeric(df.iloc[:, 3], errors='coerce') * (180 / np.pi) % 360
                except Exception as e:
                    print(f"column access failed for {csv_file}: {e}")
                    continue

                transitions = ((side_info.shift(1) != side_info) &
                               (((side_info == 'A') & (side_info.shift(1) == 'B')) |
                                ((side_info == 'B') & (side_info.shift(1) == 'A'))))

                if not transitions.any():
                    print(f"Excluded {subject_key} due to no A<->B transitions")
                    continue

                is_turn = (angle >= ANGLE_MIN) & (speed >= SPEED_MIN)
                confirmed_turns = pd.Series(False, index=is_turn.index)
                count = 0
                for i, val in enumerate(is_turn):
                    if val:
                        count += 1
                        if count >= MIN_SHARP_TURN_FRAMES:
                            confirmed_turns[i - MIN_SHARP_TURN_FRAMES + 1:i + 1] = True
                    else:
                        count = 0

                turn_counts = []
                avg_orientations_A = []
                avg_orientations_B = []
                pre_orientations_A = []
                pre_orientations_B = []
                away_A = [0] * (len(df) // FRAMES_PER_BIN + 1)
                away_B = [0] * (len(df) // FRAMES_PER_BIN + 1)

                end_frames = confirmed_turns & (~confirmed_turns.shift(-1).fillna(False))
                start_frames = confirmed_turns & (~confirmed_turns.shift(1).fillna(False))

                ori_A = [np.nan] * len(df)
                ori_B = [np.nan] * len(df)
                pre_A = [np.nan] * len(df)
                pre_B = [np.nan] * len(df)

                for idx in end_frames[end_frames].index:
                    turn_side = side_info[idx - MIN_SHARP_TURN_FRAMES + 1] if idx - MIN_SHARP_TURN_FRAMES + 1 >= 0 else None
                    post_turn = orientation[idx + 1: idx + 6]
                    if len(post_turn) > 0:
                        if turn_side == 'A':
                            ori_A[idx] = post_turn.mean()
                        elif turn_side == 'B':
                            ori_B[idx] = post_turn.mean()

                for idx in start_frames[start_frames].index:
                    turn_side = side_info[idx] if idx < len(side_info) else None
                    pre_turn = orientation[max(0, idx - 5): idx]
                    if len(pre_turn) > 0:
                        pre_mean = pre_turn.mean()
                        post_idx = end_frames[end_frames].index[end_frames[end_frames].index > idx]
                        if not post_idx.empty:
                            end_idx = post_idx[0]
                            post_mean = orientation[end_idx + 1: end_idx + 6].mean()
                            same_side = side_info[end_idx] == side_info[idx]
                            if not same_side:
                                continue
                            angle_change = lambda a1, a2: abs((a1 - a2 + 180) % 360 - 180)
                            bin_idx = idx // FRAMES_PER_BIN

                            if side == "Bottom":
                                if turn_side == 'A' and 135 <= pre_mean <= 315:
                                    if angle_change(pre_mean, 225) < angle_change(post_mean, 225):
                                        away_A[bin_idx] += 1
                                elif turn_side == 'B' and (pre_mean >= 315 or pre_mean <= 115):
                                    if angle_change(pre_mean, 45) < angle_change(post_mean, 45):
                                        away_B[bin_idx] += 1
                            elif side == "Top":
                                if turn_side == 'A' and 45 <= pre_mean <= 225:
                                    if angle_change(pre_mean, 135) < angle_change(post_mean, 135):
                                        away_A[bin_idx] += 1
                                elif turn_side == 'B' and (pre_mean >= 225 or pre_mean <= 45):
                                    if angle_change(pre_mean, 315) < angle_change(post_mean, 315):
                                        away_B[bin_idx] += 1

                    if turn_side == 'A':
                        pre_A[idx] = pre_mean
                    elif turn_side == 'B':
                        pre_B[idx] = pre_mean

                series_A = pd.Series(ori_A)
                series_B = pd.Series(ori_B)
                pre_series_A = pd.Series(pre_A)
                pre_series_B = pd.Series(pre_B)

                for i in range(0, len(confirmed_turns), FRAMES_PER_BIN):
                    segment = confirmed_turns[i:i + FRAMES_PER_BIN]
                    events = 0
                    in_event = False
                    for j in segment:
                        if j and not in_event:
                            events += 1
                            in_event = True
                        elif not j:
                            in_event = False
                    turn_counts.append(events)

                    a_seg = series_A[i:i + FRAMES_PER_BIN].dropna()
                    b_seg = series_B[i:i + FRAMES_PER_BIN].dropna()
                    pre_a_seg = pre_series_A[i:i + FRAMES_PER_BIN].dropna()
                    pre_b_seg = pre_series_B[i:i + FRAMES_PER_BIN].dropna()

                    avg_orientations_A.append(a_seg.mean() if not a_seg.empty else np.nan)
                    avg_orientations_B.append(b_seg.mean() if not b_seg.empty else np.nan)
                    pre_orientations_A.append(pre_a_seg.mean() if not pre_a_seg.empty else np.nan)
                    pre_orientations_B.append(pre_b_seg.mean() if not pre_b_seg.empty else np.nan)

                print(f"✓ {subject_key} | sharp turn events: {sum(turn_counts)}")
                result[subject_key] = turn_counts[:9]
                orientation_result_A[subject_key] = avg_orientations_A[:9]
                orientation_result_B[subject_key] = avg_orientations_B[:9]
                pre_orientation_result_A[subject_key] = pre_orientations_A[:9]
                pre_orientation_result_B[subject_key] = pre_orientations_B[:9]
                away_counts_A[subject_key] = away_A[:9]
                away_counts_B[subject_key] = away_B[:9]

    if result:
        pd.DataFrame(result).to_csv(output_csv, index=False)
        print(f"Output saved to {output_csv}")
    if orientation_result_A:
        pd.DataFrame(orientation_result_A).to_csv(orientation_csv_A, index=False)
        print(f"Side A orientation output saved to {orientation_csv_A}")
    if orientation_result_B:
        pd.DataFrame(orientation_result_B).to_csv(orientation_csv_B, index=False)
        print(f"Side B orientation output saved to {orientation_csv_B}")
    if pre_orientation_result_A:
        pd.DataFrame(pre_orientation_result_A).to_csv(pre_orientation_csv_A, index=False)
        print(f"Side A pre-turn orientation output saved to {pre_orientation_csv_A}")
    if pre_orientation_result_B:
        pd.DataFrame(pre_orientation_result_B).to_csv(pre_orientation_csv_B, index=False)
        print(f"Side B pre-turn orientation output saved to {pre_orientation_csv_B}")
    if away_counts_A:
        pd.DataFrame(away_counts_A).to_csv(away_csv_A, index=False)
        print(f"Side A turns away from midline saved to {away_csv_A}")
    if away_counts_B:
        pd.DataFrame(away_counts_B).to_csv(away_csv_B, index=False)
        print(f"Side B turns away from midline saved to {away_csv_B}")

sharpturns(
    root_dir="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc",
    output_csv="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/orientation.csv",
    orientation_csv_B="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/orientation_after_turns_B.csv",
    orientation_csv_A="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/orientation-after_turns_A.csv",
    pre_orientation_csv_A="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/pre_turns_A.csv",
    pre_orientation_csv_B="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/pre_turns_B.csv",
    away_csv_A="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/away_midline_A.csv",
    away_csv_B="/content/drive/MyDrive/09.28.25 sucrose dunce and controls/OKFINE/2025-09-28/2025-09-28/Dunce EA suc/away_midline_B.csv"
)

# BOX 8
# NUMBER OF CLOSE STOPS and AVERAGE DISTANCE TO CURRENT SIDE PORT EACH STOP IS
import os
import re
import pandas as pd
from pathlib import Path

FPS = 30
BIN_SIZE = 15  # in seconds
FRAMES_PER_BIN = BIN_SIZE * FPS
START_ROW = 2
END_ROW = 4052
MIN_STOP_FRAMES = int(0.35 * FPS)
STOP_SPEED_MAX = 4.8 * 10  # mm/s
PORT_DISTANCE_THRESHOLD = 0.9  # cm


CLOSE_PORT_A_CSV = "close_port_A_stops.csv"
CLOSE_PORT_B_CSV = "close_port_B_stops.csv"
CLOSE_PORT_A_SUM_CSV = "close_port_A_stops_sum.csv"
CLOSE_PORT_B_SUM_CSV = "close_port_B_stops_sum.csv"
AVG_DISTANCE_CSV = "average_distance_during_stops.csv"

def analyze_proximity_stops(root_dir: str, output_dir: str):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    result_A = {}
    result_B = {}
    result_A_sum = {}
    result_B_sum = {}
    avg_distance_results = {}

    for ts_folder in Path(root_dir).iterdir():
        if not re.match(r"\d+\.\d+\.\d+", ts_folder.name):
            continue

        for side in ["Top", "Bottom"]:
            side_path = ts_folder / side / "Individual CSVs"
            if not side_path.exists():
                continue

            for csv_file in side_path.glob("*Annotated.csv"):
                subject_id = csv_file.stem.replace("Annotated", "").strip(" _-")
                subject_key = f"{ts_folder.name}_{side}_{subject_id}"

                try:
                    df_full = pd.read_csv(csv_file, skiprows=START_ROW)
                    df = df_full.iloc[:END_ROW - START_ROW + 1]
                    speed = pd.to_numeric(df.iloc[:, 13], errors='coerce') * 10
                    side_info = df.iloc[:, 30].astype(str)
                    port_dist_A = pd.to_numeric(df.iloc[:, 35], errors='coerce')
                    port_dist_B = pd.to_numeric(df.iloc[:, 36], errors='coerce')
                except Exception as e:
                    print(f"Error processing {csv_file}: {e}")
                    continue

                n_bins = len(df) // FRAMES_PER_BIN
                stop_counts_A = [0] * n_bins
                stop_counts_B = [0] * n_bins
                avg_distances = []

                for b in range(n_bins):
                    i_start = b * FRAMES_PER_BIN
                    i_end = min(i_start + FRAMES_PER_BIN, len(df))

                    in_stop = False
                    stop_len = 0
                    stop_start = None
                    distances_during_stops = []

                    for i in range(i_start, i_end):
                        if pd.isna(speed[i]):
                            continue

                        if speed[i] <= STOP_SPEED_MAX:
                            if not in_stop:
                                in_stop = True
                                stop_start = i
                                stop_len = 1
                            else:
                                stop_len += 1
                        else:
                            if in_stop and stop_len >= MIN_STOP_FRAMES:
                                stop_side = side_info[stop_start]
                                if stop_side == 'A' and (port_dist_A[stop_start:stop_start + stop_len] <= PORT_DISTANCE_THRESHOLD).all():
                                    stop_counts_A[b] += 1
                                    distances_during_stops.extend(port_dist_A[stop_start:stop_start + stop_len])
                                elif stop_side == 'B' and (port_dist_B[stop_start:stop_start + stop_len] <= PORT_DISTANCE_THRESHOLD).all():
                                    stop_counts_B[b] += 1
                                    distances_during_stops.extend(port_dist_B[stop_start:stop_start + stop_len])
                            in_stop = False
                            stop_len = 0

                    if in_stop and stop_len >= MIN_STOP_FRAMES:
                        stop_side = side_info[stop_start]
                        if stop_side == 'A' and (port_dist_A[stop_start:stop_start + stop_len] <= PORT_DISTANCE_THRESHOLD).all():
                            stop_counts_A[b] += 1
                            distances_during_stops.extend(port_dist_A[stop_start:stop_start + stop_len])
                        elif stop_side == 'B' and (port_dist_B[stop_start:stop_start + stop_len] <= PORT_DISTANCE_THRESHOLD).all():
                            stop_counts_B[b] += 1
                            distances_during_stops.extend(port_dist_B[stop_start:stop_start + stop_len])

                    if distances_during_stops:
                        avg_distance = sum(distances_during_stops) / len(distances_during_stops)
                    else:
                        avg_distance = float('nan')
                    avg_distances.append(avg_distance)

                result_A[subject_key] = stop_counts_A
                result_B[subject_key] = stop_counts_B
                result_A_sum[subject_key] = sum(stop_counts_A[3:])
                result_B_sum[subject_key] = sum(stop_counts_B[3:])
                avg_distance_results[subject_key] = avg_distances

    if result_A:
        pd.DataFrame(result_A).to_csv(Path(output_dir) / CLOSE_PORT_A_CSV, index=False)
    if result_B:
        pd.DataFrame(result_B).to_csv(Path(output_dir) / CLOSE_PORT_B_CSV, index=False)
    if result_A_sum:
        pd.DataFrame.from_dict(result_A_sum, orient='index', columns=["Sum_Stop_Counts_A_from_45s"]).to_csv(Path(output_dir) / CLOSE_PORT_A_SUM_CSV)
    if result_B_sum:
        pd.DataFrame.from_dict(result_B_sum, orient='index', columns=["Sum_Stop_Counts_B_from_45s"]).to_csv(Path(output_dir) / CLOSE_PORT_B_SUM_CSV)
    if avg_distance_results:
        pd.DataFrame(avg_distance_results).to_csv(Path(output_dir) / AVG_DISTANCE_CSV, index=False)

analyze_proximity_stops(
    "",
    ""
)

# BOX 9
# distance travelled per region
import os
import re
import pandas as pd
from pathlib import Path
import math


FPS = 30
FRAMES_PER_BIN = 15 * FPS  # 150 frames per 5-second bi
START_ROW = 0
END_ROW = 4050
MIN_SHARP_TURN_FRAMES = int(0.15 * FPS)
MIN_STOP_FRAMES = int(0.35 * FPS)


ANGLE_MIN = 4.0  # deg/.05s
SPEED_MIN = 5.0  # mm/s

STOP_SPEED_MAX = 4.8 * 10  # mm/s
STOP_ANGLE_MAX = 5.7  # deg/.05s
STOP_ACC_MAX = 1.0 * 10  # mm/s²

def analyze_sharp_turns(root_dir: str, output_dir: str, mean_stop_start: int = 1800, mean_stop_end: int = 4050):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    sharp_turns_csv = output_dir / "sharp_turns.csv"
    sharp_turns_A_csv = output_dir / "sharp_turns_A.csv"
    sharp_turns_B_csv = output_dir / "sharp_turns_B.csv"
    stops_csv = output_dir / "stops.csv"
    stops_A_csv = output_dir / "stops_A.csv"
    stops_B_csv = output_dir / "stops_B.csv"
    mean_stop_duration_csv = output_dir / "mean_stop_durations.csv"
    short_subjects_log = output_dir / "short_subjects_log.csv"
    distance_A_csv = output_dir / "distance_region_A.csv"
    distance_B_csv = output_dir / "distance_region_B.csv"
    distance_log_csv = output_dir / "distance_bin_debug_log.csv"

    turn_result = {}
    stop_result = {}
    turn_result_A = {}
    turn_result_B = {}
    stop_result_A = {}
    stop_result_B = {}
    mean_stop_durations = {}
    padded_subjects = []
    distance_A = {}
    distance_B = {}
    distance_log = []

    for ts_folder in Path(root_dir).iterdir():
        if not re.match(r"\d+\.\d+\.\d+", ts_folder.name):
            continue

        for side in ["Top", "Bottom"]:
            side_path = ts_folder / side / "Individual CSVs"
            if not side_path.exists():
                continue

            for csv_file in side_path.glob("*Annotated.csv"):
                subject_id = csv_file.stem.replace("Annotated", "").strip(" _-")
                subject_key = f"{ts_folder.name}_{side}_{subject_id}"

                try:
                    df_full = pd.read_csv(csv_file, skiprows=START_ROW)
                    df = df_full.iloc[:END_ROW - START_ROW + 1]
                    acc = pd.to_numeric(df.iloc[:, 2], errors='coerce') * 10
                    speed = pd.to_numeric(df.iloc[:, 13], errors='coerce') * 10
                    angle = pd.to_numeric(df.iloc[:, 5], errors='coerce')
                    side_info = df.iloc[:, 30].astype(str)
                    dist_moved = pd.to_numeric(df.iloc[:, 33], errors='coerce')
                except Exception as e:
                    print(f"Error processing {csv_file}: {e}")
                    continue

                transitions = ((side_info == 'A') & (side_info.shift(1) == 'B')) | \
                              ((side_info == 'B') & (side_info.shift(1) == 'A'))
                if not transitions.any():
                    continue

                frame_count = len(df)
                bin_count = math.ceil(frame_count / FRAMES_PER_BIN)

                distance_bins_A = []
                distance_bins_B = []
                for i in range(0, len(dist_moved), FRAMES_PER_BIN):
                    region = side_info[i:i + FRAMES_PER_BIN]
                    dist = dist_moved[i:i + FRAMES_PER_BIN]
                    region_A = dist[region == 'A'].sum(skipna=True)
                    region_B = dist[region == 'B'].sum(skipna=True)
                    distance_bins_A.append(region_A if not pd.isna(region_A) else 0)
                    distance_bins_B.append(region_B if not pd.isna(region_B) else 0)

                distance_A[subject_key] = distance_bins_A  # keep all bins
                distance_B[subject_key] = distance_bins_B

                distance_log.append({
                    "subject": subject_key,
                    "frame_count": frame_count,
                    "bin_count": len(distance_bins_A),
                    "truncated_at": bin_count if len(distance_bins_A) > bin_count else "none"
                })

    if distance_A:
        pd.DataFrame(distance_A).to_csv(distance_A_csv, index=False)
    if distance_B:
        pd.DataFrame(distance_B).to_csv(distance_B_csv, index=False)
    if distance_log:
        pd.DataFrame(distance_log).to_csv(distance_log_csv, index=False)

    if turn_result:
        pd.DataFrame(turn_result).to_csv(sharp_turns_csv, index=False)
        pd.DataFrame(turn_result_A).to_csv(sharp_turns_A_csv, index=False)
        pd.DataFrame(turn_result_B).to_csv(sharp_turns_B_csv, index=False)
        print("Sharp turn data saved.")
    else:
        print("No valid sharp turn data found.")

    if stop_result:
        pd.DataFrame(stop_result).to_csv(stops_csv, index=False)
        pd.DataFrame(stop_result_A).to_csv(stops_A_csv, index=False)
        pd.DataFrame(stop_result_B).to_csv(stops_B_csv, index=False)
        pd.DataFrame.from_dict(mean_stop_durations, orient='index', columns=['mean_stop_duration_seconds']).to_csv(mean_stop_duration_csv)
        print("Stop data saved.")
    else:
        print("No valid stop data found.")

    if padded_subjects:
        pd.DataFrame(padded_subjects).to_csv(short_subjects_log, index=False)
        print(f"Logged padded subjects to {short_subjects_log}")

analyze_sharp_turns(
    "",
    "",
    mean_stop_start=0,
    mean_stop_end=4050
)

# BOX 10
# DIST TRAVELLED PER SIDE GRAPH
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from glob import glob

from matplotlib.patches import Rectangle

def load_csv_group(csv_dir, keyword):
    files = sorted(glob(os.path.join(csv_dir, f"*{keyword}*.csv")))
    dataframes = [pd.read_csv(f, header=None, skiprows=1) for f in files]
    return dataframes, files

def filter_paired_subjects(h20_dfs, sucrose_dfs):
    filtered_h20 = []
    filtered_sucrose = []
    for h20_df, suc_df in zip(h20_dfs, sucrose_dfs):
        if h20_df.sum().sum() == 0 or suc_df.sum().sum() == 0:
            continue  # exclude both sides if one has all zeros
        filtered_h20.append(h20_df)
        filtered_sucrose.append(suc_df)
    return filtered_h20, filtered_sucrose

def compute_mean_sem(dataframes):
    aligned = []
    for df in dataframes:
        df = df.dropna().reset_index(drop=True)
        aligned.append(df)
    all_data = pd.concat(aligned, axis=1, ignore_index=True)
    print(f"[INFO] Concatenated data shape: {all_data.shape} (bins x columns)")
    mean = all_data.mean(axis=1)
    sem = all_data.sem(axis=1)
    return mean.values, sem.values

def format_x_labels(num_bins):
    return [f"{i*5}-{i*5+5}" if i % 3 == 0 else "" for i in range(num_bins)]

def smooth(data, sigma=1):
    from scipy.ndimage import gaussian_filter1d
    return gaussian_filter1d(data, sigma)

def plot_combined_data(csv_dir, output_dir, smooth_lines=False, sigma=1, y_max_override=None, x_max_override=None):
    os.makedirs(output_dir, exist_ok=True)

    h20_dfs, _ = load_csv_group(csv_dir, "H20")
    sucrose_dfs, _ = load_csv_group(csv_dir, "sucrose")

    if not h20_dfs or not sucrose_dfs:
        raise ValueError("No matching csvs found for H20 or sucrose.")

    h20_dfs, sucrose_dfs = filter_paired_subjects(h20_dfs, sucrose_dfs)

    if not h20_dfs or not sucrose_dfs:
        raise ValueError("found no subject pairs with movement in both conditions.")

    h20_mean, h20_sem = compute_mean_sem(h20_dfs)
    sucrose_mean, sucrose_sem = compute_mean_sem(sucrose_dfs)

    if smooth_lines:
        h20_mean = smooth(h20_mean, sigma)
        sucrose_mean = smooth(sucrose_mean, sigma)

    num_bins = len(h20_mean)
    x = np.arange(num_bins)
    x_labels = format_x_labels(num_bins)

    plt.figure(figsize=(10, 6))
    ax = plt.gca()
    ax.set_xlim([0, x_max_override if x_max_override is not None else num_bins - 1])

    def add_shaded_region(ax, start_bin, end_bin, color, label):
        ymin, ymax = ax.get_ylim()
        ax.axvspan(start_bin, end_bin, color=color, alpha=0.3, zorder=0)
        x_label_pos = (start_bin + 0.2)
        ax.text(x_label_pos, ymax * 2.95, label, rotation=0,
                verticalalignment='top', horizontalalignment='left',
                fontsize=14, color='black', zorder=3)

    add_shaded_region(ax, 0, 3, 'lavender', 'Odor Off')
    add_shaded_region(ax, 3, 9, 'honeydew', 'Choosing')
    add_shaded_region(ax, 9, 27, 'white', 'Post-Choice')

    ax.axvline(x=3, color='gray', linestyle='--', linewidth=1, zorder=0)
    ax.axvline(x=9, color='gray', linestyle='--', linewidth=1, zorder=0)

    ax.plot(x, h20_mean, color='steelblue', label='H20', linewidth=3, zorder=2)
    ax.fill_between(x, h20_mean - h20_sem, h20_mean + h20_sem,
                    color='steelblue', alpha=0.075, zorder=2)

    ax.plot(x, sucrose_mean, color='darkblue', label='Sucrose', linewidth=3, zorder=2)
    ax.fill_between(x, sucrose_mean - sucrose_sem, sucrose_mean + sucrose_sem,
                    color='blue', alpha=0.075, zorder=2)

    y_min_default = 0.5
    y_max_default = max(np.max(h20_mean + h20_sem), np.max(sucrose_mean + sucrose_sem)) * 1.05
    ax.set_ylim([y_min_default, y_max_override if y_max_override is not None else y_max_default])

    ax.set_xticks(x)
    ax.set_xticklabels(x_labels, fontsize=15, rotation=45)

    y_ticks = np.arange(0.5, ax.get_ylim()[1] + 0.25, 0.25)
    y_labels = [f"{tick:.2f}" if i % 2 == 0 else '' for i, tick in enumerate(y_ticks)]
    ax.set_yticks(y_ticks)
    ax.set_yticklabels(y_labels, fontsize=15)

    ax.set_xlabel("Time Bins", fontsize=16, fontweight='bold')
    ax.set_ylabel("Distance (cm)", fontsize=16, fontweight='bold')
    ax.legend(loc='upper right', fontsize=14)
    plt.tight_layout()

    out_path = os.path.join(output_dir, "combined_plot.pdf")
    plt.savefig(out_path)
    plt.close()

# Example usage:
plot_combined_data(
    "",
    "",
    smooth_lines=False,
    sigma=2,
    y_max_override=3.0,
    x_max_override=26
)